project-management/1-1-meetings/Vicky-Hellon/weekly-meetings.md

Thank you so much for the fantastic work! 🌸

Update notes for weekly meeting with Vicky

---

project-management/1-1-meetings/Vicky-Hellon/weekly-meetings.md

Thank you for the PR Vicky. Really glad to see the progress! 🌸

Update weekly-meetings.md with comments

---

project-management/1-1-meetings/Arron-Lacey/weekly-meetings.md

added to weekly update

---

project-management/1-1-meetings/Vicky-Hellon/weekly-meetings.md

ready for your notes @malvikasharan

18 jan notes vh

---

project-management/1-1-meetings/Vicky-Hellon/weekly-meetings.md

VH notes 1 feb

---

project-management/1-1-meetings/Achintya-Rao/weekly-meetings.md

[AR] Add notes for weekly meeting (2022-02-08)

---

project-management/1-1-meetings/Achintya-Rao/weekly-meetings.md

[AR] Add notes for meetings on 2022-02-15 and 2022-03-10

---

project-management/1-1-meetings/Achintya-Rao/weekly-meetings.md

[AR] Add notes for 2022-03-22 meeting

---

project-management/1-1-meetings/Anne-Lee-Steele/weekly-meetings.md

Adding in notes for both last week & this week's meeting. Please let me know if there anything I've forgotten!

update for 2 weeks: 22-29 mar

---

project-management/1-1-meetings/Achintya-Rao/weekly-meetings.md

[AR] Add meeting notes for 2022-04-11

---

project-management/1-1-meetings/Anne-Lee-Steele/weekly-meetings.md

@aleesteele Thank you so much for the fantastic work already within a short period in The Turing Way. I am really grateful for you taking on a lot from my plate already.
My general advice for you is to slow down a bit in May and start to review your notes (see [if this timeline is indeed complete or massive revision is needed](https://hackmd.io/E8CUcdUnRUO12y0G1vAGbw#Responsibilities)). I think there is a lot of things that need to be picked up for deeper dive from your existing notes and I am worried that if we don't take the time to reflect more often it will lead to many unfinished or last minute tasks.
Besides, as always, Thank you for your thoughtful planning and organisation in The Turing Way.

Adding comments to ALS' notes as I see them missing

---

README.md

Hi Team!
I've added my name to the list of team members in this PR.

Update Team Members list: added Sophia

---

project-management/1-1-meetings/Achintya-Rao/weekly-meetings.md

[AR] Add notes for 2022-05-03 and 2022-05-11 meetings

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Added my weekly updates for Tuesday 10 May, 2022.

10-5-22 Weekly Updates

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Added my updates for week of 17 May 2022. 
Notes: 
- the dates table of contents aren't embedding as quick links, I would appreciate a second pair of eyes on the formatting to checked what I've missed

Weekly updates 17.05.22

---

project-management/1-1-meetings/Vicky-Hellon/weekly-meetings.md

17 may notes

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Added some updates for this week ⭐

Added weekly updates

---

project-management/1-1-meetings/Achintya-Rao/weekly-meetings.md

[AR] Add notes for 2022-05-31 (async)

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Added some weekly updates for this week 🌟

Weekly updates 31-05-2022

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Weekly updates for 21 June 2022

Week Updates 2022-06-21

---

project-management/1-1-meetings/Sophia-Batchelor/github-explore.md

I created a starting file to use for GitHub explorations.

Create exploration file

---

project-management/1-1-meetings/Sophia-Batchelor/github-explore.md

Update explore file

---

project-management/1-1-meetings/Sophia-Batchelor/github-explore.md

added my name to the explore file

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Added some updates for the week and added in the points discussed today.

Weekly updates 28 June

---

project-management/1-1-meetings/Eirini-Zormpa/weekly-meetings-emma.md

Hi Emma, I've added some reflections for our meeting tomorrow :blush:

20220628 eirini emma meeting

---

project-management/1-1-meetings/Achintya-Rao/weekly-meetings.md

[AR] Add notes for 2022-06-21 and 2022-07-05 meetings

---

project-management/1-1-meetings/Achintya-Rao/misc-meetings/2022-06-23.md

Adding ASG specific notes for the timeline.

asg timeline based on notes are added

---

project-management/1-1-meetings/Eirini-Zormpa/weekly-meetings-evelina.md

Hi Evelina, I added some reflections for our meeting tomorrow 😊

20220629 eirini evelina meeting

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

July 12 Updates

---

project-management/1-1-meetings/Achintya-Rao/weekly-meetings.md

[AR] Add notes for meetings on 2022-07-20 and 2022-07-26

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Weekly Updates: 29 July '22

---

project-management/1-1-meetings/Achintya-Rao/weekly-meetings.md

[AR] Add notes for 2022-08-02 meeting

---

CODE_OF_CONDUCT.md

- Adding Code of Conduct for the team.
- Ask all members to review and leave a comment if they are happy to have this Code of Conduct added to the project
- Need the restorative justice element to be discussed and reviewed with @KirstieJane

Add code of conduct for the team

---

project-management/1-1-meetings/Anne-Lee-Steele/weekly-meetings.md

Anne week 21

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Weekly updates 26 August

---

project-management/1-1-meetings/Achintya-Rao/weekly-meetings.md

[AR] Add notes for 2022-08-11 meeting

---

project-management/1-1-meetings/Anne-Lee-Steele/weekly-meetings.md

adding notes for this week: overlapping with maintenance work!

notes: 9 aug 2022

---

project-management/1-1-meetings/Achintya-Rao/weekly-meetings.md

[AR] Add notes for 2022-08-30 and 2022-09-06 meetings

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Added updates for September 14th 🚀

SB Weekly Updates 

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Added initial updates for sept 20

Sept 20 updates

---

project-management/1-1-meetings/Eirini-Zormpa/weekly-meetings-emma.md

I've added my reflections for the weekly meeting with EK on 14 September in the weekly-meetings-emma.md file

added reflections for weekly meeting on 14 September

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Weekly Update 27 September

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Added notes for week beginning 3rd October.

Added weekly meeting notes

---

project-management/1-1-meetings/Eirini-Zormpa/weekly-meetings-evelina.md

I've added some notes for the 5 October meeting

added notes for meeting with Evelina on 5 October

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings.md

Updates 25 Nov 22

---

project-management/1-1-meetings/Sophia-Batchelor/meetings-template-2023.md
project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings-2023.md

PR to create files for BGT + SB meetings 
What's Changed:
---
* Created a separate file for the meeting template 
* Created a new weekly meetings file (titled weekly-meetings-2023) for meeting notes

Sb handover meeting

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings-2023.md

* Added updates for the weekly meeting

Weekly updates 6 Dec 23

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings-2023.md

What's New
---
* Added updates for 13 Dec meeting
Additional Information 
---
Had to make a "push to `main`" PR to save work when my laptop crashed so all updates aren't reflected in this PR. However the full update is captured in the correct section.

Weekly updates 13 Dec

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings-2023.md

Added weekly updates for 10 Jan 2023

Update weekly meetings

---

project-management/1-1-meetings/Anne-Lee-Steele/weekly-meetings.md

- Notes for sept 21 for MS to review

Anne updates - 20 sept

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings-2023.md

- Updates for 14 feb
- Updates for 21 feb

Sb updates february 

---

project-management/1-1-meetings/Sophia-Batchelor/weekly-meetings-2023.md

Added updates for 2 May 2023 and have outlined a loose agenda for today's meeting.

Weekly Updates 2 May 2023

---

resources/presentations/README.md

What Changed
---
I added the presentation slides from today's presentation to the Project Management Unit about using GitHub for project management. 
What to Review
---

Presentations folder update

---

CODE_OF_CONDUCT.md

About this PR
---
I noticed a few typos while reviewing the document. 
I fixed typo on line 44
- there are 3 other typos I noticed but have not "re found" so am happy to patch this one and then wait for fresh eyes to find the others I saw earlier. 
What to focus a review on:
---
- do you want all typos fixed before merging?

Fixed typo

---

project-management/team-meetings/2023-08-07-rcm-team-meetings.md

reviewed and redacted confidential or identifiable information from meeting minutes.

add notes from 2023-08-07-rcm-team-meeting

---

CODE_OF_CONDUCT.md

Updating the language to align with the conversation with Kirstie and @gedankenstuecke on how to enforce CoC for employee

Update CODE_OF_CONDUCT.md to update the enforcement for employee

---

README.md

We had a team day this week where we discussed some principles that informs the updates in our guiding principles - suggested in this PR.

Update README.md to update guiding principles

---

project-management/1-1-meetings/Eirini-Zormpa/weekly-meetings-emma.md

Update EZ weekly-meetings-emma.md

---

project-management/1-1-meetings/gabin-kayumbi/meeting-notes.md

Thanks for the meeting Gabin. Please add the missing info.
Many exciting things to follow up on! Also, the launch meeting agenda looks amazing - excited to attend that with you. 
Let's put a shared document for note taking for the day.
We should follow up on some of the agenda discussed during our next meeting.

GK biweekly notes [missing details]

---

project-management/1-1-meetings/Alexandra-AraujoAlvarez/2024_04_16.md

Adding the 1-1 Notes from April to August 2024
